# Generated by Django 2.2.4 on 2019-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esehi',
            name='username',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
