# Generated by Django 2.2.4 on 2019-08-11 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keshu.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_auto_20190811_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esehi',
            name='userid',
            field=models.ForeignKey(default=keshu.middleware.CurrentUserMiddleware.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
