# Generated by Django 2.2.4 on 2019-08-11 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('child', '0005_auto_20190811_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esehi',
            name='userid',
        ),
        migrations.AddField(
            model_name='esehi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
