# Generated by Django 2.2.7 on 2020-02-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_auto_20190812_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost',
            fields=[
                ('esehi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='child.esehi')),
            ],
            bases=('child.esehi',),
        ),
    ]
