# Generated by Django 2.2.7 on 2020-02-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_lost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lost',
        ),
    ]
