# Generated by Django 2.2.7 on 2020-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_delete_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='esehi',
            name='perms',
            field=models.BooleanField(default=False),
        ),
    ]
