# Generated by Django 2.2.20 on 2021-05-23 15:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0013_auto_20210316_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='missing',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
